spring.application.name=boot-catalog
spring.profiles.active=dev

spring.datasource.driver-class-name=org.postgresql.Driver

# upload
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# jwt
app.jwt.expiration-ms=86400000

# Batch: Flyway gestiona el schema, Spring no debe intentarlo
spring.batch.jdbc.initialize-schema=never

# Batch: NO lanzar jobs automáticamente al arrancar (los lanzamos bajo demanda)
spring.batch.job.enabled=false
