INSERT INTO platforms (name, short_name) VALUES
    ('PlayStation 1', 'PS1'),
    ('PlayStation 2', 'PS2'),
    ('PlayStation 3', 'PS3'),
    ('PlayStation 4', 'PS4'),
    ('PlayStation 5', 'PS5'),
    ('PlayStation Portable', 'PSP'),
    ('PlayStation Vita', 'PSV'),
    ('Nintendo Entertainment System', 'NES'),
    ('Super Nintendo', 'SNES'),
    ('Nintendo 64', 'N64'),
    ('Nintendo GameCube', 'GCN'),
    ('Nintendo Wii', 'Wii'),
    ('Nintendo Wii U', 'WiiU'),
    ('Nintendo Switch', 'NSW'),
    ('Game Boy', 'GB'),
    ('Game Boy Advance', 'GBA'),
    ('Nintendo DS', 'NDS'),
    ('Nintendo 3DS', '3DS'),
    ('Sega Master System', 'SMS'),
    ('Sega Genesis', 'GEN'),
    ('Sega Saturn', 'SAT'),
    ('Sega Dreamcast', 'DC'),
    ('Xbox', 'XBOX'),
    ('Xbox 360', 'X360'),
    ('Xbox One', 'XONE'),
    ('Xbox Series X|S', 'XSX'),
    ('PC', 'PC');
